name: Daily News Bot

on:
  schedule:
    # Run every 4 hours: 8 AM, 12 PM, 4 PM, 8 PM IST
    - cron: '30 2 * * *'   # 8:00 AM IST
    - cron: '30 6 * * *'   # 12:00 PM IST (Noon)
    - cron: '30 10 * * *'  # 4:00 PM IST
    - cron: '30 14 * * *'  # 8:00 PM IST
  workflow_dispatch:  # Allows manual testing

jobs:
  post-news:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run news bot
      env:
        NEWSAPI_KEY: ${{ secrets.NEWSAPI_KEY }}
        GEMINI_KEY: ${{ secrets.GEMINI_KEY }}
        X_API_KEY: ${{ secrets.X_API_KEY }}
        X_API_SECRET: ${{ secrets.X_API_SECRET }}
        X_ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
        X_ACCESS_SECRET: ${{ secrets.X_ACCESS_SECRET }}
      run: python agent.py
